Repository slackapi/bolt-python, pull requests merged in 2022-11, with the labels that each got.

#755 version 1.15.2.dev0
  slack_bolt/version.py
Labels: improvement

#751 Add Python 3.11 to the supported language versions
  .github/workflows/tests.yml
  setup.py
Labels: docs

#766 Fix #763 by improving the suggestion logging for view_closed patterns
  slack_bolt/logger/messages.py
  tests/slack_bolt/logger/test_unmatched_suggestions.py
  tests/slack_bolt_async/logger/test_unmatched_suggestions.py
Labels: area:async, improvement, area:sync

#769 Fix #768 The client arg in a listener does not respect the singleton WebClient's retry_handlers
  slack_bolt/app/app.py
  slack_bolt/app/async_app.py
  tests/scenario_tests/test_web_client_customization.py
  tests/scenario_tests_async/test_web_client_customization.py
Labels: bug, area:async, area:sync

#770 Fix #757 by using Falcon 3.1.1
  .github/workflows/tests.yml
  setup.py
Labels: area:async, area:adapter, area:sync

#776 CI python 3.6 bug fix
  .github/workflows/tests.yml
Labels: bug

#761 Add next-gen future documentation
  .gitignore
  docs/Gemfile
  docs/_config.yml
  docs/_future/concepts.md
  docs/_future/deploy_your_app.md
  docs/_future/getting_started_future.md
  docs/_future/listening_responding_functions.md
  docs/_future/manifest.md
  docs/_future/manifest_functions.md
  docs/_future/manifest_workflows.md
  docs/_future/setup_existing_app.md
  docs/_includes/head.html
  docs/_includes/sidebar.html
  docs/_layouts/default.html
  docs/_layouts/future.html
  docs/_steps/adding_editing_workflow_step.md
  docs/_steps/creating_workflow_step.md
  docs/api-docs/slack_bolt/app/app.html
  docs/api-docs/slack_bolt/app/async_app.html
  docs/api-docs/slack_bolt/app/index.html
  docs/api-docs/slack_bolt/async_app.html
  docs/api-docs/slack_bolt/context/base_context.html
  docs/api-docs/slack_bolt/index.html
  docs/api-docs/slack_bolt/listener_matcher/builtins.html
  docs/api-docs/slack_bolt/middleware/async_builtins.html
  docs/api-docs/slack_bolt/middleware/message_listener_matches/async_message_listener_matches.html
  docs/api-docs/slack_bolt/middleware/message_listener_matches/index.html
  docs/api-docs/slack_bolt/middleware/message_listener_matches/message_listener_matches.html
  docs/api-docs/slack_bolt/oauth/async_oauth_settings.html
  docs/api-docs/slack_bolt/oauth/oauth_settings.html
  docs/api-docs/slack_bolt/request/async_request.html
  docs/api-docs/slack_bolt/request/index.html
  docs/api-docs/slack_bolt/request/internals.html
  docs/api-docs/slack_bolt/request/request.html
  docs/api-docs/slack_bolt/util/utils.html
  docs/api-docs/slack_bolt/workflows/step/async_step.html
  docs/api-docs/slack_bolt/workflows/step/index.html
  docs/api-docs/slack_bolt/workflows/step/step.html
  docs/assets/style.css
  docs/scripts/future_search_hash.js
Labels: docs
