Repository slackapi/bolt-python, pull requests merged in 2022-09, with the labels that each got.

#718 [future beta] Adding remote function view interactivity
  slack_bolt/listener_matcher/builtins.py
  slack_bolt/slack_function/slack_function.py
  tests/scenario_tests/test_function_decorators.py
  tests/scenario_tests/test_function_view_closed.py
  tests/scenario_tests/test_function_view_submission.py
Labels: enhancement, area:sync

#719 [future beta] Adding async capabilities to remote functions interactivity
  slack_bolt/app/async_app.py
  slack_bolt/middleware/async_builtins.py
  slack_bolt/middleware/attaching_function_token/async_attaching_function_token.py
  slack_bolt/request/async_internals.py
  slack_bolt/slack_function/slack_function.py
  tests/scenario_tests_async/test_function_block_action.py
  tests/scenario_tests_async/test_function_decorators.py
  tests/scenario_tests_async/test_function_view_closed.py
  tests/scenario_tests_async/test_function_view_submission.py
Labels: enhancement, area:async

#722 Fix #721 Passing a global dict object without channel prop can cause issues among requests
  slack_bolt/context/say/async_say.py
  slack_bolt/context/say/say.py
  tests/slack_bolt/context/test_say.py
  tests/slack_bolt_async/context/test_async_say.py
Labels: enhancement, area:async, area:sync

#727 Bump Sanic package to v22.x
  setup.py
Labels: area:async, area:adapter, improvement

#725 Development release steps in guide
  .github/maintainers_guide.md
  scripts/deploy_to_pypi_org.sh
  scripts/deploy_to_test_pypi_org.sh
Labels: docs
