Repository slackapi/bolt-python, pull requests merged in 2023-11, with the labels that each got.

#987 Fix SocketMode Test
  tests/adapter_tests/socket_mode/test_interactions_websocket_client.py
  tests/utils.py
Labels: bug

#990 Fix #988 app.action listener should accept block_id-only constraints for bolt-js feature parity
  slack_bolt/listener_matcher/builtins.py
  tests/scenario_tests/test_block_actions.py
  tests/scenario_tests_async/test_block_actions.py
Labels: bug

#991 Improve socket mode tests
  tests/adapter_tests/socket_mode/mock_socket_mode_server.py
  tests/adapter_tests/socket_mode/test_interactions_builtin.py
  tests/adapter_tests/socket_mode/test_interactions_websocket_client.py
  tests/adapter_tests/socket_mode/test_lazy_listeners.py
  tests/adapter_tests_async/socket_mode/test_async_aiohttp.py
  tests/adapter_tests_async/socket_mode/test_async_lazy_listeners.py
  tests/adapter_tests_async/socket_mode/test_async_websockets.py
Labels: improvement

#996 Configuring with pyproject.toml
  .github/maintainers_guide.md
  .github/workflows/codecov.yml
  .github/workflows/tests.yml
  pyproject.toml
  pytest.ini
  requirements.txt
  requirements/adapter.txt
  requirements/adapter_testing.txt
  requirements/async.txt
  requirements/testing.txt
  requirements/testing_without_asyncio.txt
  scripts/build_pypi_package.sh
  scripts/deploy_to_pypi_org.sh
  scripts/deploy_to_test_pypi_org.sh
  scripts/install_all_and_run_tests.sh
  scripts/run_pytype.sh
  scripts/run_tests.sh
  setup.cfg
  setup.py
Labels: improvement, discussion
