Repository slackapi/bolt-python, pull requests merged in 2024-09, with the labels that each got.

#1143 disc: remove the optional typing of client
  slack_bolt/authorization/async_authorize.py
  slack_bolt/authorization/async_authorize_args.py
  slack_bolt/authorization/authorize.py
  slack_bolt/authorization/authorize_args.py
  slack_bolt/context/async_context.py
  slack_bolt/context/context.py
  slack_bolt/middleware/attaching_function_token/async_attaching_function_token.py
  slack_bolt/middleware/attaching_function_token/attaching_function_token.py
  slack_bolt/middleware/authorization/async_multi_teams_authorization.py
  slack_bolt/middleware/authorization/async_single_team_authorization.py
  slack_bolt/middleware/authorization/multi_teams_authorization.py
  slack_bolt/middleware/authorization/single_team_authorization.py
Labels: bug

#1155 chore: group docusaurus dependencies
  .github/dependabot.yml
Labels: docs, dependencies

#1161 Update opening-modals.md (removed extra s)
  docs/content/basic/opening-modals.md
Labels: cla:signed

#1164 docs: simplify authorization.md Python code
  docs/content/advanced/authorization.md
Labels: docs, cla:signed

#1170 Fix double quoted img alt text
  slack_bolt/oauth/internals.py
  tests/adapter_tests_async/test_async_falcon.py
  tests/adapter_tests_async/test_async_fastapi.py
  tests/adapter_tests_async/test_async_sanic.py
  tests/adapter_tests_async/test_async_starlette.py
Labels: bug, cla:signed
